using System.Collections.Generic;
using Mandrill;
using NUnit.Framework;

namespace TalBrodyTests
{
    [TestFixture]
    public class MailTest
    {
        [Test]
        public void EmailTest()
        {
            return;
            var api = new MandrillApi("J0BCtrmARKDInbkE0Xw3TQ");
            var email = new EmailMessage
            {
                to = new List<EmailAddress> {new EmailAddress("test@oxify.co", "Test Oxify User")},
                from_email = "team@oxify.co",
                from_name = "Oxify",
                subject = "Test Oxify email",
                html = "<p><b>Hello from Oxify!</b></p><p>This test email was generated by your mama</p>"
            };


            api.SendMessage(email);
        }
    }
}
